### ISSUE TITLE
[BUG] Cannot boot Asus Chromebook, after software Shut Down of Ubuntu 22.04

### ISSUE THREAD

**Issue by sdaau** [eupnea-linux/depthboot-builder#65] opened 2023-04-15 14:31 UTC
**Describe the bug**

I had recently got a new Asus Chromebook CX1400CNA, and I successfully used depthboot to install Ubuntu 22.04 cli (where I eventually installed Mate Desktop).

In the past days that I've had it, I experienced this twice: have Ubuntu 22.04 booted; charge the battery to 100%; Shut Down from the Ubuntu menu; the device shuts down. After some delay (minutes up to hours), I try to boot the device again - it will not boot. Both times this is after a Shut Down command from Ubuntu; if I do Suspend from Ubuntu, that usually works fine (ok, maybe network would not work after Ubuntu Suspend, but then I could do Ubuntu restart, and that worked).

The first time I experienced this, I managed to somehow boot the device again. The second time - now - I cannot turn the device on anymore. Here is a video:

https://user-images.githubusercontent.com/26737749/232230173-60460b03-ad23-4781-881e-1e74a5290c83.mp4

In review:

* (Original) charger plugged in, LED shines white; press or press-and-hold Power button - nothing happens
* (Original) charger plugged in, LED shines white; press Refresh + Power button: LED blinks off once, then it keeps shining white, nothing else happens
* Charger disconnected, LED does not shine: press or press-and-hold Power button - nothing happens
* Charger disconnected, LED does not shine: press Refresh + Power button: LED blinks white once, then it keeps being off (not shining), nothing else happens

I have also tried this: https://support.google.com/chromebook/thread/182709565/my-chromebook-won-t-turn-on-and-the-lights-don-t-work

> This is a method that sometimes works on devices that won't turn on:
> 
> 1. Connect the charger to the Chrome OS device.
> 2. Hold the power button + Refresh key  and remove the power adaptor as they keep holding on to those buttons.
> 3. Wait for 1 minute.
> 4. Press the power button to test the device.
> (4a) Note: The power LED should not blink and the device should not turn on.
> 5. Connect the power adaptor and monitor the LED colour. The device should try to turn on and the LED should blink or have a solid colour.

I can reproduce the same up to and including step 4a. For step 5, first the LED turns on white, then it briefly changes color to orange (or red? cannot really see, it is quite brief), then it goes back to shining white, and ignoring power on requests.

I have a suspicion that the device is now bricked - and this seems to be explicitly a result of doing Shut Down from Ubuntu.

Is there any way to recover this machine, and have it boot again?

**To Reproduce**

See above

**Full log**

No log in this case,

**Build system (please complete the following information):**
 - OS: Ubuntu 20.04
 
**Additional context**

I have a `collect-logs` from this machine in https://github.com/eupnea-linux/audio-scripts/issues/49

**Comment by Apacelus** [comment] 2023-04-15 14:34
Can you replicate the behavior in ChromeOS

**Comment by sdaau** [comment] 2023-04-15 14:39
Thanks @Apacelus : 

> Can you replicate the behavior in ChromeOS

What do you mean? I was under the impression that a depthboot installation deletes ChromeOS? At least, I could confirm  it it deleted most of the original ChromeOS partitions after Ubuntu got installed... So I'm pretty sure I do not have Chrome OS on this Chromebook anymore ?

**Comment by Apacelus** [comment] 2023-04-15 15:23
1. Depthboot doesnt delete ChromeOS, unlesd **you** chose to do so, by running `install-to-internal` in the Terminal
2. Reinstall ChromeOS and check if you can replicate

**Comment by sdaau** [comment] 2023-04-15 15:31
Thanks @Apacelus : 

> 1. Depthboot doesnt delete ChromeOS, unless **you** chose to do so, by running `install-to-internal` in the Terminal

Ah, yes, you're absolutely right - sorry, I don't have much experience with this, so I forgot that detail: I indeed did do `install-to-internal` specifically, because I do not have any personal need for ChromeOS

> 2. Reinstall ChromeOS and check if you can replicate

Is this doable if I did do `install-to-internal`?

If you mean that I should reinstall ChromeOS via USB thumbdrive, the problem is that the device does not react to Ctrl-Refresh-Power either, so I cannot get to a boot menu (from where I could install ChromeOS image from USB thumbdrive)

**Comment by Apacelus** [comment] 2023-04-15 19:37
> Is this doable if I did do install-to-internal?Is this doable if I did do install-to-internal?

Depthboot in no way prevents you from reinstalling ChromeOS.

> If you mean that I should reinstall ChromeOS via USB thumbdrive, the problem is that the device does not react to Esc-Refresh-Power either, so I cannot get to a boot menu (from where I could install ChromeOS image from USB thumbdrive)

I will not try to solve this until I am certain that the issue is with Depthboot and not just the Chromebook itself. Therfor you will need to somehow reinstall ChromeOS to make sure that it is not a hardware issue

**Comment by sdaau** [comment] 2023-04-15 20:23
Thanks for the feedback @Apacelus : 

> Depthboot in no way prevents you from reinstalling ChromeOS.

Good to know - I was unsure.

> I will not try to solve this until I am certain that the issue is with Depthboot and not just the Chromebook itself

Understandable - the problem is:

> Therefor you will need to somehow reinstall ChromeOS

... I don't know how to do that now. I don't mind trying to do that, but I'm at a loss what my options are, or even what to do. If I cannot boot from thumbdrive to reflash, and the device is already bricked, what possible other options are there to "somehow" reinstall Chrome OS?

**Comment by WeirdTreeThing** [comment] 2023-04-15 20:38
> Charger disconnected, LED does not shine: press Refresh + Power button: LED blinks white once, then it keeps being off (not shining), nothing else happens

The problem might be that the battery is somehow not providing enough power to the device to keep it on. Make sure the charger you are using is the original one that came with the device or another one powerful enough to power the device (45W+).

**Comment by sdaau** [comment] 2023-04-15 21:55
Thanks @WeirdTreeThing - just to confirm, it is the original charger I've used most of the time, including the video (though after about an hour of dead device, I did try booting with a weaker charger a couple of times, but that did not make any difference, and I went back to the original charger)

**Comment by WeirdTreeThing** [comment] 2023-04-15 22:54
Sounds like a hardware problem then.

**Comment by Apacelus** [comment] 2023-04-22 15:11
Closing due to it being highly likely a hardware problem and not a software one

**Closed by Apacelus** 2023-04-22 15:11 UTC
